### ISSUE TITLE
Trying to add this to my site

### ISSUE THREAD

**Issue by nsmsn** [CodeFoodPixels/eleventy-plugin-webmentions#2]
I upgraded to the latest version of eleventy and went through the steps on [Luke's post](https://lukeb.co.uk/blog/2022/06/28/no-comment-2-the-webmentioning/) and the readme. 

Trying to use the plugin's filters, I copied some of the code from Luke's site's [post.njk template](https://github.com/CodeFoodPixels/lukeb.co.uk/blob/master/src/_includes/layouts/post.njk)

On my local build I am getting these errors: 

```
`TemplateWriterWriteError` was thrown
> (./src/_includes/layouts/post.njk)
  Error: filter not found: webmentionCountForPage
```

```
`Template render error` was thrown:
    Template render error: (./src/_includes/layouts/post.njk)
      Error: filter not found: webmentionCountForPage
        at Object._prettifyError (/.../nicksimsondotcom/node_modules/nunjucks/src/lib.js:36:11)
        at /.../nicksimsondotcom/node_modules/nunjucks/src/environment.js:563:19
        at Template.root [as rootRenderFunc] (eval at _compile (/.../nicksimsondotcom/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:91:3)
        at Template.render (/.../nicksimsondotcom/node_modules/nunjucks/src/environment.js:552:10)
        at /.../nicksimsondotcom/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:236:14
        at new Promise (<anonymous>)
        at /.../nicksimsondotcom/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:235:14
        at TemplateLayout.render (/.../nicksimsondotcom/node_modules/@11ty/eleventy/src/TemplateLayout.js:152:31)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Template.renderPageEntry (/.../nicksimsondotcom/node_modules/@11ty/eleventy/src/Template.js:603:17)
```

Is there something I may be overlooking?

**Comment by CodeFoodPixels** [comment]
Is your code anywhere to look at? Like your templates and
.eleventyconfig.js?

**Comment by nsmsn** [comment]
Thanks for taking a look. Here's my repo: [https://github.com/nsmsn/nicksimsondotcom](https://github.com/nsmsn/nicksimsondotcom)

The eleventy-plugin-webmentions files installed successfully in my node_modules folder.

The error failed to deploy my site to Netlify, but you can see where I'm trying to use the filters in my own [post.njk](https://github.com/nsmsn/nicksimsondotcom/blob/master/src/_includes/layouts/post.njk).

I also included `<link rel="webmention">` code in my base.njk file

**Comment by CodeFoodPixels** [comment]
Ah, I see the issue. In your .eleventy.js you've got 2 module.exports if
you merge them together (e.g put the webmentions .addplugin call with the
ones in the other one) then it will work

**Comment by nsmsn** [comment]
Thanks! I did this, but I'm still getting the same error in the build. 

```
`TemplateWriterWriteError` was thrown
> (./src/_includes/layouts/post.njk)
  Error: filter not found: webmentionCountForPage

`Template render error` was thrown:
    Template render error: (./src/_includes/layouts/post.njk)
      Error: filter not found: webmentionCountForPage
```

I committed the changes again. Can you check out my [eleventy.js](https://github.com/nsmsn/nicksimsondotcom/blob/master/.eleventy.js) file and [post.njk](https://github.com/nsmsn/nicksimsondotcom/blob/master/src/_includes/layouts/post.njk)?

**Comment by CodeFoodPixels** [comment]
Just noticed in your package.json that you're using Eleventy 0.12.1, this
plugin requires version 1.0.0 at a minimum

**Comment by nsmsn** [comment]
Thanks. I ran an update command in my project, but that must not have done it. Thanks for helping me out with this--I'll close the issue and try updating to the latest version of Eleventy again.

**Comment by nsmsn** [comment]
I updated Eleventy to 1.0.1 in my project and successfully deployed. This time when I try to add the webmentions to my post.njk file (locally) I get a new error:

`TypeError: webmentions.filter is not a function`

**Comment by CodeFoodPixels** [comment]
Could I have some more context for this? That line isn't something in my
code

**Comment by CodeFoodPixels** [comment]
Closing as there's been no response for 23 days.
