### ISSUE TITLE
Allow for line breaks in comments

### ISSUE THREAD

**Issue by rangermeier** [CodeFoodPixels/eleventy-plugin-webmentions#3]
I'd like to display webmention comments on my blog with line breaks as in the original post on mastodon/twitter/...

It appears that sanitize-html strips line feeds `\n` when processing HTML strings. I couldn't find any documentation on how sanitize-html treats white-space and line feeds.

Would it be possible to implement an additional option to eleventy-plugin-webmentions, i.e. `htmlConvertNewLines`  or `htmlNl2br` (naming things is hard), that would replace any `\n` to `<br>` before passing the HTML strings to the sanitizer?

**Comment by CodeFoodPixels** [comment]
I've just realised that this impacts my site too! I'll have to have a dig
into it and have a look

**Comment by CodeFoodPixels** [comment]
Fixed in v2.0.0. If you specify that you want HTML, it will convert blocks of text separated by `\n` into paragraphs wrapped by the `<p>` tag
